export const PLAYER_HEADSHOT_ALIASES: Readonly<Record<string, string>> = {
  mekhimcniel: "mehkimcniel",
  nazvereen: "nazvareen",
  pasqualevillano: "pasqualevilliano",
  julianallen: "idk",
};

export const MISSING_PLAYER_HEADSHOT_KEYS: ReadonlySet<string> = new Set<string>([
  "edmundscott",
  "terongriffin",
  "terrongriffin",
  "khalidmoreland",
  "ryanboehm",
  "mikeyfuller",
  "tiyornecoleman",
  "jamesjackson",
  "alexbeliard",
  "alandbeliard",
  "jaylencrawford",
  "kylefederici",
  "jermainefoster",
  "javonwilson",
  "permjackson",
  "anthonymiller",
  "dashonsmith",
  "darricmyers",
  "derricmyers",
  "nickbottone",
  "tylermarchese",
  "malikcameron",
  "colbywinchester",
  "howiemiller",
  "jaylindavis",
  "lukeyoder",
  "ericcummings",
  "markischristie",
  "henrysmith",
  "jahwancody",
  "brandonholland",
  "siahtait",
  "addengoffe",
  "sheriffbilewu",
  "willbarton",
  "anthonyireland",
  "lateefbilewu",
]);
